# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Tests and Collect Coverage and make Badge

on:
  pull_request:
    branches: ["develop"]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest --cov=myapp --cov-report=xml --cov-fail-under=70

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if badge alredy in place
        run: |
          if grep -q "![Build Status](https://github.com/finkord/basicGitHubAcrtionsWorkflow/actions/workflows/pytest_workflow.yml/badge.svg)" README.md; then
            echo "Badge alredy exists."
            echo "update_needed=false" >> $GITHUB_ENV
          else
            echo "update_needed=true" >> $GITHUB_ENV
          fi

      - name: Add badge if needed
        if: env.update_needed == 'true'
        run: |
          echo "<!-- BUILD-STATUS-BADGE --> 
          ![Build Status](https://github.com/${{ github.repository }}/actions/workflows/pytest_workflow.yml/badge.svg)" | cat - README.md > temp && mv temp README.md

      - name: commit and push changes
        if: env.update_needed == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git fetch --all
          git checkout ${{ github.head_ref }}

          git add README.md
          git commit -m "Added badge to README"
          git push
